controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


app_post_remove_tag:
    path: /post/{id}/remove-tag/{tagId}
    controller: App\Controller\PostController::removeTagFromPost